# shellcheck shell=bash
alias ll='ls -lhA'
alias la='ls -A'
alias l='ls -CF'
alias cd..='cd ..'
alias here='find . -name '
alias df='df -Tha --total'
alias du='du -ach | sort -h'
alias free='free -mt'
alias psg='ps aux | grep -v grep | grep -i -e VSZ -e'
alias mkdir='mkdir -pv'
alias wget='wget -c'
alias myip='curl http://ipecho.net/plain; echo'
alias python='python3'
alias c='clear'
alias update='update_os'
alias attach='tmux attach-session -t '
alias tnew='tmux new -s '
alias activate='source venv/bin/activate'
alias f='cd "$(find ~ -type d \( -name node_modules -o -name .git \) -prune -o -type d -print | fzf)"'
alias fcp='filecopy'
alias build='dotnet restore && dotnet clean && dotnet build'
alias run='dotnet run --urls http://localhost:5001'
alias watch='dotnet watch run --urls http://localhost:5001'
alias hib='sudo systemctl hibernate'
alias whichterminal='ps -p $(ps -p $$ -o ppid=) -o args'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

alias cn='create_note.sh'
alias snf='find_note_file.sh'
alias snt='find_note_tag.sh'
alias dn='delete_note.sh'

command -v srm >/dev/null 2>&1 && alias rm='srm -i -v'

[ -n "${WAYLAND_DISPLAY:-}" ] && alias claude='env -u DISPLAY claude'
